name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 8 ]
    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: :99
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Install Opera
      if: matrix.os == 'ubuntu-latest'
      run: |
        wget -O - http://deb.opera.com/archive.key | sudo apt-key add -
        sudo sh -c 'echo "deb http://deb.opera.com/opera-stable/ stable non-free" >> /etc/apt/sources.list.d/opera.list'
        sudo apt-get update
        sudo apt-get install opera-stable
    - name: Start Xvfb
      if: matrix.os == 'ubuntu-latest'
      run: |
        Xvfb $DISPLAY &
    - name: Run tests
      run: |
        mvn -B test
